[server]
address = "0.0.0.0" # address to bind to
api_domain = "localhost"
port = 8080 # the port to bind to
trusted_proxies = ["127.0.0.1"]
debug_mode = false # use of gin's debug mode (includes verbose logging)
hide_requests = false # requests should be hidden from logs
allowed_origins = [ "http://localhost" ] # cors allowed origins

[server.tls]
enabled = false
cert_file = "/path/to/cert"
key_file = "/path/to/keyfile"

[encryption]
key_size = 16

[files]
# directory for uploaded files
uploads_dir = "uploads" 

# general toggle for whether files are deleted after specific time or not
remove_files_after_inactivity = true

# set to be true if site uses SSL
auth_use_secure_cookie = false

# file inactivity until delete e.g. how long the file has to be idle before removing
inactivity_until_delete = "86400s"

# how long client authentication lasts
auth_save_time = "1900s"

# following restriction rules are in bytes
# maximum size for a single upload that is not encrypted by the server
max_single_upload_size = 100000000 # 100mb
# total maximum size that a client can upload during one day
max_upload_size_per_day = 100000000 # 100mb
# maximum size for a single upload that is encrypted by the server
max_encryptable_file_size = 100000000 # 100mb

[ratelimit.strict_limit]
requests = 3
# time until reset
time = 180

[ratelimit.query_limit]
requests = 2
# time until reset
time = 60

[database]
user  = "usva"
password = "usva"
host = "127.0.0.1"
port = 5432
database = "usva"
use_ssl = false
