[Server]
Address = "127.0.0.1" # address to bind to
Port = 8080 # the port to bind to
TrustedProxies = ["127.0.0.1"]
DebugMode = false # use of gin's debug mode (includes verbose logging)
HideRequests = false # requests should be hidden from logs
AllowedOrigins = [ "http://localhost" ] # cors allowed origins

[Server.TLS]
Enabled = false
CertFile = "/path/to/cert"
KeyFile = "/path/to/keyfile"

[Files]
# Maximum size for a single upload in bytes. In this configuration set to 1 Mb
# Zero (0) disables this field. (ratelimit is bypassed)
MaxSingleUploadSize = 1048576

# Maximum size for uploads per day per IP. In this configuration this value is
# set to 16 Mb.
# Zero (0) disables this field. (ratelimit is bypassed)
MaxUploadSizePerDay = 16777216

# UploadsDir describes the path in current filesystem where uploaded files are saved.
UploadsDir = "uploads" # directory for uploaded files

RemoveFilesAfterInactivity = true

# File maximum inactivity in seconds until delete
InactivityUntilDelete = 86400

# Cleantrashes boolean specifies if server should remove all files that are not present in database.
# this can be optimal but dangerous at the same time, if you haven't verified that usva
# correctly reads the target directory. In the worst case scenario your important files are gone!
CleanTrashes          = false

[Ratelimit.StrictLimit]
Requests = 3
Time = 180

[Ratelimit.QueryLimit]
Requests = 2
Time = 60

[Database]
User  = "dev"
Password = ""
Host = "127.0.0.1"
Port = 5432
Database = "usva"
