version: "3.8"

services:
  db:
    image: "postgres:14.5"
    restart: always

    environment:
      POSTGRES_USER: ${DB_USERNAME_TESTS:-usva_tests}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TESTS:-testrunner}

    ports:
      - ${DB_PORT:-5432}:5432

    volumes:
      - "./${TEST_CACHE:-.test-cache/postgres}:/var/lib/postgresql/data:rw"