name: push-validation
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0

      - name: Unit Testing
        run: DB_PORT=15432 make migratesetup test
      - name: Building
        run: make build
