name: push-validation
on: [push]
jobs:
  validity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run linter
        uses: golangci/golangci-lint-action@v3.2.0

      - name: Database migrations
        run: make preparetests

      - name: Unit testing
        run: make test

      - name: Building
        run: make build
